"""Prepare user-supplied cave entrances for Map Studio's KOTOR portal kit.

The source OBJ files are detailed visual shells, not walkmesh owners.  This
script copies them into the repository, removes the small blocking insert from
the Korriban entrance, preserves source UV/normal indices, and creates
engine-safe 2048 px TGA diffuse maps.  Continuous floors, tunnel throats, and
WOK portals are generated by the authored-room connection system.

Run from the repository root:
    py -3.14 scripts/prepare_cave_portal_assets.py
"""

from __future__ import annotations

import hashlib
import json
import shutil
from collections import defaultdict, deque
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = Path(
    r"C:\Users\NewAdmin\Documents\KotorMods\ModdersResourceFiles\CustomProps\Environment"
)
OUTPUT_ROOT = ROOT / "assets" / "map_studio" / "terrain_kits" / "cave_portals"
MANIFEST_PATH = OUTPUT_ROOT / "cave_portal_assets.json"

ASSETS = (
    {
        "asset_id": "korriban_cave_entrance",
        "source_obj": "Caves/KorribanCaveEntrance1Mirrored.obj",
        "source_texture": "Caves/KorribanCaveEntrance1_basecolor.jpg",
        "output_stem": "KorribanCaveEntranceMirrored",
        "texture_resref": "gr_korrentr",
        "source_units": "centimeters",
        "drop_small_rear_component": True,
        "style": "korriban_tombs",
    },
    {
        "asset_id": "shyrack_cave_entrance",
        "source_obj": "Caves/ShyrackCaveEntranceMirrored.obj",
        "source_texture": "Caves/ShyrackCaveEntranceMirrored_basecolor.jpg",
        "output_stem": "ShyrackCaveEntranceMirrored",
        "texture_resref": "gr_shyrentr",
        "source_units": "meters",
        "drop_small_rear_component": False,
        "style": "korriban_caves_k1",
    },
    {
        "asset_id": "shadowlands_module_transition",
        "source_obj": "Shadowlands/Shadowlandsmoduletransition1.obj.obj",
        "source_texture": "Shadowlands/Shadowlandsmoduletransition1.obj_basecolor.jpg",
        "output_stem": "ShadowlandsModuleTransition",
        "texture_resref": "gr_shadentr",
        "source_units": "meters",
        "drop_small_rear_component": False,
        "style": "shadowlands",
    },
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _face_vertex_indices(tokens: list[str]) -> tuple[int, ...]:
    return tuple(int(token.split("/", 1)[0]) for token in tokens[1:])


def _filtered_korriban_obj(source: Path, target: Path, *, mtllib_name: str) -> dict[str, int]:
    """Drop the isolated rear doorway insert while retaining OBJ indices.

    KorribanCaveEntrance1 has three face-connected components.  The smallest
    component sits deep behind the arch and closes most of the traversal
    aperture.  The rock mound and carved arch are retained without reindexing,
    so all source vt/vn references remain byte-for-byte meaningful.
    """

    lines = source.read_text(encoding="utf-8", errors="replace").splitlines()
    faces: list[tuple[int, tuple[int, ...], list[str]]] = []
    vertex_to_faces: dict[int, list[int]] = defaultdict(list)
    for line_index, line in enumerate(lines):
        tokens = line.strip().split()
        if not tokens or tokens[0] != "f":
            continue
        vertices = _face_vertex_indices(tokens)
        face_index = len(faces)
        faces.append((line_index, vertices, tokens))
        for vertex in vertices:
            vertex_to_faces[vertex].append(face_index)

    adjacency: list[set[int]] = [set() for _ in faces]
    for attached in vertex_to_faces.values():
        for face_index in attached:
            adjacency[face_index].update(attached)
    components: list[list[int]] = []
    unseen = set(range(len(faces)))
    while unseen:
        seed = unseen.pop()
        component: list[int] = []
        queue: deque[int] = deque((seed,))
        while queue:
            current = queue.popleft()
            component.append(current)
            for neighbor in adjacency[current]:
                if neighbor in unseen:
                    unseen.remove(neighbor)
                    queue.append(neighbor)
        components.append(component)
    components.sort(key=len, reverse=True)
    if len(components) < 3:
        raise RuntimeError(
            f"Expected three Korriban entrance components, found {len(components)}."
        )
    retained_faces = set(index for component in components[:2] for index in component)
    source_line_to_face = {line_index: face_index for face_index, (line_index, _vertices, _tokens) in enumerate(faces)}
    output: list[str] = []
    for line_index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("mtllib "):
            output.append(f"mtllib {mtllib_name}")
            continue
        face_index = source_line_to_face.get(line_index)
        if face_index is not None and face_index not in retained_faces:
            continue
        output.append(line)
    target.write_text("\n".join(output) + "\n", encoding="utf-8")
    return {
        "source_component_count": len(components),
        "source_triangle_count": len(faces),
        "retained_triangle_count": len(retained_faces),
        "removed_triangle_count": len(faces) - len(retained_faces),
    }


def _copy_obj(source: Path, target: Path, *, mtllib_name: str) -> dict[str, int]:
    lines = source.read_text(encoding="utf-8", errors="replace").splitlines()
    triangle_count = 0
    output: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("mtllib "):
            output.append(f"mtllib {mtllib_name}")
        else:
            output.append(line)
        if stripped.startswith("f "):
            triangle_count += max(1, len(stripped.split()) - 3)
    target.write_text("\n".join(output) + "\n", encoding="utf-8")
    return {
        "source_component_count": 1,
        "source_triangle_count": triangle_count,
        "retained_triangle_count": triangle_count,
        "removed_triangle_count": 0,
    }


def _write_mtl(source_obj: Path, target: Path, *, texture_name: str) -> None:
    """Write only the materials the selected OBJ actually uses."""

    used = tuple(
        dict.fromkeys(
            line.strip().split(maxsplit=1)[1]
            for line in source_obj.read_text(encoding="utf-8", errors="replace").splitlines()
            if line.strip().startswith("usemtl ") and len(line.strip().split(maxsplit=1)) == 2
        )
    )
    if not used:
        used = ("module_transition_material",)
    rows: list[str] = []
    for material_name in used:
        rows.extend(
            (
                f"newmtl {material_name}",
                "illum 2",
                "Kd 1.000000 1.000000 1.000000",
                "Ka 1.000000 1.000000 1.000000",
                "Ks 0.000000 0.000000 0.000000",
                "d 1.000000",
                f"map_Kd {texture_name}",
                "",
            )
        )
    target.write_text("\n".join(rows), encoding="utf-8")


def _write_texture(source: Path, target: Path) -> tuple[int, int]:
    with Image.open(source) as image:
        converted = image.convert("RGBA")
        converted.thumbnail((2048, 2048), Image.Resampling.LANCZOS)
        converted.save(target, format="TGA", rle=True)
        return converted.size


def main() -> int:
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    rows: list[dict[str, object]] = []
    for asset in ASSETS:
        output_stem = str(asset["output_stem"])
        source_obj = SOURCE_ROOT / str(asset["source_obj"])
        source_texture = SOURCE_ROOT / str(asset["source_texture"])
        for required in (source_obj, source_texture):
            if not required.is_file():
                raise FileNotFoundError(required)

        target_obj = OUTPUT_ROOT / f"{output_stem}.obj"
        target_mtl = OUTPUT_ROOT / f"{output_stem}.mtl"
        target_tga = OUTPUT_ROOT / f"{asset['texture_resref']}.tga"
        if bool(asset["drop_small_rear_component"]):
            topology = _filtered_korriban_obj(
                source_obj,
                target_obj,
                mtllib_name=target_mtl.name,
            )
        else:
            topology = _copy_obj(
                source_obj,
                target_obj,
                mtllib_name=target_mtl.name,
            )
        _write_mtl(target_obj, target_mtl, texture_name=target_tga.name)
        texture_size = _write_texture(source_texture, target_tga)
        rows.append(
            {
                **asset,
                **topology,
                "source_path": str(source_obj),
                "obj": target_obj.name,
                "mtl": target_mtl.name,
                "texture": target_tga.name,
                "texture_size": list(texture_size),
                "obj_sha256": _sha256(target_obj),
                "texture_sha256": _sha256(target_tga),
                "visual_shell_only": True,
                "walkmesh_owner": "generated_transition_floor",
            }
        )

    MANIFEST_PATH.write_text(
        json.dumps(
            {
                "schema": "ghostrigger.cave-portal-assets/v1",
                "source_license": "user-supplied modder resources",
                "assets": rows,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(json.dumps({"output": str(OUTPUT_ROOT), "assets": rows}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
