"""Build UTC/NCS resources for authored Map Studio creature behavior.

The GIT creature row owns only template identity and transform. Faction,
conversation, perception, scripts, durability, and movement behavior live in
the referenced UTC. This service patches the smallest useful UTC behavior
surface without importing Qt or mutating a source game resource.
"""

from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Any

from pykotor.common.misc import Game, ResRef
from pykotor.resource.formats.gff import bytes_gff, read_gff
from pykotor.resource.formats.ncs import bytes_ncs, compile_nss


_RESREF_PATTERN = re.compile(r"^[A-Za-z0-9_]{1,16}$")
_FACTION_ROLES = {
    "player": 0,
    "hostile": 1,
    "hostile_1": 1,
    "friendly": 2,
    "friendly_1": 2,
    "hostile_2": 3,
    "friendly_2": 4,
    "neutral": 5,
}
_MOVEMENT_MODES = {"stationary", "free_roam"}


@dataclass(frozen=True)
class AuthoredCreatureBehaviorBuild:
    """Patched creature template and optional compiled movement script."""

    template_resref: str
    faction_id: int
    conversation_resref: str
    movement_mode: str
    source_spawn_script: str
    spawn_script_resref: str
    nss_source: str
    resources: tuple[tuple[str, str, bytes], ...]


def _resref(value: Any, label: str, *, allow_blank: bool = False) -> str:
    text = str(value or "").strip().lower()
    if "." in text:
        text = text.rsplit(".", 1)[0]
    if not text and allow_blank:
        return ""
    if not _RESREF_PATTERN.fullmatch(text):
        raise ValueError(f"{label} must be a 1-16 character KOTOR resref using letters, numbers, or underscores.")
    return text


def _game(value: Game | str) -> Game:
    if isinstance(value, Game):
        return value
    token = str(value or "").strip().upper()
    if token in {"K1", "KOTOR", "KOTOR1"}:
        return Game.K1
    if token in {"K2", "TSL", "KOTOR2"}:
        return Game.K2
    raise ValueError("Creature behavior game must be K1 or K2.")


def _faction_id(value: int | str) -> int:
    if isinstance(value, str) and not value.strip().isdigit():
        key = value.strip().lower().replace("-", "_").replace(" ", "_")
        if key not in _FACTION_ROLES:
            known = ", ".join(sorted(_FACTION_ROLES))
            raise ValueError(f"Unknown creature faction role '{value}'. Known roles: {known}.")
        return _FACTION_ROLES[key]
    try:
        faction_id = int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError("Creature faction must be a standard role or non-negative repute.2da row.") from exc
    if faction_id < 0 or faction_id > 0xFFFF:
        raise ValueError("Creature FactionID must fit the UTC uint16 field.")
    return faction_id


def _roam_script_resref(template_resref: str, requested: Any = "") -> str:
    if str(requested or "").strip():
        return _resref(requested, "Free-roam OnSpawn script")
    return _resref(f"{template_resref[:11]}_roam", "Free-roam OnSpawn script")


def _free_roam_nss(source_spawn_script: str) -> str:
    preserved = ""
    if source_spawn_script:
        preserved = f'    ExecuteScript("{source_spawn_script}", OBJECT_SELF);\n'
    return (
        "// Generated by GhostRigger Map Studio.\n"
        "// ActionRandomWalk is the engine-native free-roam action; authored\n"
        "// waypoint patrols use a separate GN_WalkWayPoints workflow.\n"
        "void main() {\n"
        f"{preserved}"
        "    ActionRandomWalk();\n"
        "}\n"
    )


def build_authored_creature_behavior_resources(
    source_utc_bytes: bytes,
    *,
    game: Game | str,
    template_resref: str,
    instance_tag: str = "",
    faction_role: int | str,
    conversation_resref: str | None = None,
    movement_mode: str = "stationary",
    spawn_script_resref: str = "",
) -> AuthoredCreatureBehaviorBuild:
    """Patch a copied UTC and return export-ready ``extra_resources`` rows.

    ``stationary`` does not erase the source template's OnSpawn behavior; it
    simply adds no roaming override. ``free_roam`` emits a deterministic NCS
    that first executes the source OnSpawn script, when present, then queues
    the engine-native ``ActionRandomWalk`` action.
    """

    raw = bytes(source_utc_bytes or b"")
    if not raw:
        raise ValueError("Creature behavior authoring requires source UTC bytes.")
    target_game = _game(game)
    template = _resref(template_resref, "Creature template")
    faction_id = _faction_id(faction_role)
    mode = str(movement_mode or "stationary").strip().lower().replace("-", "_")
    if mode not in _MOVEMENT_MODES:
        raise ValueError("Creature movement mode must be 'stationary' or 'free_roam'.")

    gff = read_gff(raw)
    root = gff.root
    source_spawn = _resref(
        root.acquire("ScriptSpawn", ResRef.from_blank()),
        "Source UTC OnSpawn script",
        allow_blank=True,
    )
    root.set_resref("TemplateResRef", template)
    tag = str(instance_tag or template).strip()[:32]
    if not tag:
        tag = template
    root.set_string("Tag", tag)
    root.set_uint16("FactionID", faction_id)
    if conversation_resref is not None:
        root.set_resref(
            "Conversation",
            _resref(conversation_resref, "Creature conversation", allow_blank=True),
        )
    conversation = _resref(
        root.acquire("Conversation", ResRef.from_blank()),
        "Creature conversation",
        allow_blank=True,
    )

    script_resref = ""
    nss_source = ""
    resources: list[tuple[str, str, bytes]] = []
    if mode == "free_roam":
        script_resref = _roam_script_resref(template, spawn_script_resref)
        nss_source = _free_roam_nss(source_spawn)
        ncs_bytes = bytes_ncs(compile_nss(nss_source, target_game))
        root.set_resref("ScriptSpawn", script_resref)
        resources.append((script_resref, "ncs", ncs_bytes))

    utc_bytes = bytes_gff(gff)
    resources.insert(0, (template, "utc", utc_bytes))
    return AuthoredCreatureBehaviorBuild(
        template_resref=template,
        faction_id=faction_id,
        conversation_resref=conversation,
        movement_mode=mode,
        source_spawn_script=source_spawn,
        spawn_script_resref=script_resref,
        nss_source=nss_source,
        resources=tuple(resources),
    )


__all__ = [
    "AuthoredCreatureBehaviorBuild",
    "build_authored_creature_behavior_resources",
]
