"""Headless authored module metadata compiler for Map Studio.

This module owns the Map Studio policy for turning editable module/area
metadata into ARE and IFO resources.  It stays Qt-free so the future metadata
inspector can call the same compiler used by smoke exports.
"""

from __future__ import annotations

import hashlib
import math
from dataclasses import dataclass, field, replace
from typing import Any

from .authored_module_objects import ModuleEntryPoint, apply_entry_point_to_ifo
from .authored_module_project import (
    AuthoredModuleMetadata,
    authored_resref_blocking_issue,
    normalise_resref,
)

RGB = tuple[int, int, int]
FULLBRIGHT_LIGHTING_PROFILE = "fullbright"
AREA_SCRIPT_FIELDS: tuple[str, ...] = ("OnEnter", "OnExit", "OnHeartbeat", "OnUserDefined")
MODULE_SCRIPT_FIELDS: tuple[str, ...] = (
    "Mod_OnHeartbeat",
    "Mod_OnModLoad",
    "Mod_OnModStart",
    "Mod_OnClientEntr",
    "Mod_OnClientLeav",
    "Mod_OnActvtItem",
    "Mod_OnAcquirItem",
    "Mod_OnUsrDefined",
    "Mod_OnUnAqreItem",
    "Mod_OnPlrDeath",
    "Mod_OnPlrDying",
    "Mod_OnPlrLvlUp",
    "Mod_OnSpawnBtnDn",
    "Mod_OnPlrRest",
)


@dataclass(frozen=True)
class AuthoredAreaMetadata:
    """Editable ARE metadata for an authored module area."""

    name: str = ""
    tag: str = ""
    comments: str = "Generated by GhostRigger Map Studio."
    unescapable: bool = False
    disable_transit: bool = False
    natural: bool = True
    player_vs_player: bool = False
    no_rest: bool = False
    sun_ambient: RGB = (64, 64, 64)
    sun_diffuse: RGB = (255, 255, 255)
    fog_color: RGB = (0, 0, 0)
    fog_near: float = 100.0
    fog_far: float = 200.0
    sun_fog_on: bool = False
    # K1 exterior ARE fields.  Keeping them first-class means a custom
    # Shadowlands clearing exports the same terrain layer as the retail rooms
    # it connects to rather than losing grass when no stock ARE is preserved.
    grass_texture: str = ""
    grass_density: float = 0.0
    grass_quad_size: float = 0.0
    grass_prob_ll: float = 0.25
    grass_prob_lr: float = 0.25
    grass_prob_ul: float = 0.25
    grass_prob_ur: float = 0.25
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AuthoredModuleTimeMetadata:
    """Editable IFO time/progression metadata."""

    dawn_hour: int = 6
    dusk_hour: int = 18
    minutes_per_hour: int = 2
    expansion_pack: int = 0


@dataclass(frozen=True)
class AuthoredModuleMetadataValidation:
    ok: bool
    warnings: tuple[str, ...] = ()
    blocking_issues: tuple[str, ...] = ()


@dataclass(frozen=True)
class CompiledAuthoredModuleMetadata:
    """Serialized ARE/IFO output plus validation/provenance."""

    are_bytes: bytes
    ifo_bytes: bytes
    validation: AuthoredModuleMetadataValidation
    metadata: dict[str, Any] = field(default_factory=dict)


def _new_gff(content_name: str) -> Any:
    from pykotor.resource.formats.gff import GFF
    from pykotor.resource.formats.gff.gff_data import GFFContent

    return GFF(getattr(GFFContent, content_name))


def _new_struct() -> Any:
    from pykotor.resource.formats.gff.gff_data import GFFStruct

    return GFFStruct()


def _empty_gff_list() -> Any:
    from pykotor.resource.formats.gff.gff_data import GFFList

    return GFFList()


def _bytes_gff(gff: Any) -> bytes:
    from pykotor.resource.formats.gff import bytes_gff

    return bytes_gff(gff)


def _locstring(text: str) -> Any:
    from pykotor.common.language import LocalizedString

    return LocalizedString.from_english(text)


def _empty_locstring() -> Any:
    from pykotor.common.language import LocalizedString

    return LocalizedString.from_invalid()


def _set_loc(root: Any, label: str, text: str) -> None:
    try:
        root.set_locstring(label, _locstring(text))
    except Exception:
        root.set_string(label, text)


def _rgb(value: RGB) -> int:
    red = max(0, min(255, int(value[0])))
    green = max(0, min(255, int(value[1])))
    blue = max(0, min(255, int(value[2])))
    return (red << 16) | (green << 8) | blue


def _byte(value: bool) -> int:
    return 1 if bool(value) else 0


def _is_k2_game(game: Any) -> bool:
    text = str(game or "K1").strip().upper()
    return text in {"K2", "TSL", "KOTOR2", "KOTOR II"}


def _are_version_for_game(game: Any) -> int:
    return 345 if _is_k2_game(game) else 193


def _module_id_bytes(root_resref: str) -> bytes:
    """Return a stable 16-byte module ID for deterministic smoke packages."""

    root = normalise_resref(root_resref)
    return hashlib.md5(f"ghostrigger:module:{root}".encode("ascii", errors="ignore")).digest()


def authored_module_id_bytes(root_resref: str) -> bytes:
    """Return GhostRigger's deterministic runtime module identity bytes."""

    return _module_id_bytes(root_resref)


def _set_empty_resref(root: Any, label: str) -> None:
    root.set_resref(label, "")


def _dict(value: Any) -> dict[str, Any]:
    return dict(value) if isinstance(value, dict) else {}


def _packed_rgb(value: Any, fallback: RGB) -> RGB:
    """Decode a KOTOR packed ``0xRRGGBB`` color into an RGB tuple."""

    try:
        packed = int(value)
    except (TypeError, ValueError):
        return fallback
    return ((packed >> 16) & 0xFF, (packed >> 8) & 0xFF, packed & 0xFF)


def _legacy_are_lighting_metadata(value: Any) -> dict[str, Any]:
    """Normalize the ARE dictionary stored by older stock-module imports."""

    source = _dict(value)
    if not source:
        return {}
    nested = _dict(source.get("lighting"))
    if nested:
        return nested
    if not any(
        key in source
        for key in (
            "sun_ambient_color",
            "sun_diffuse_color",
            "dyn_ambient_color",
            "shadow_opacity",
            "sun_shadows",
        )
    ):
        return {}
    return {
        "profile": "standard",
        "source": "map_studio:stock_are_compat",
        "sun_ambient": list(_packed_rgb(source.get("sun_ambient_color"), (64, 64, 64))),
        "sun_diffuse": list(_packed_rgb(source.get("sun_diffuse_color"), (255, 255, 255))),
        "dynamic_ambient": list(_packed_rgb(source.get("dyn_ambient_color"), (64, 64, 64))),
        "shadow_opacity": source.get("shadow_opacity", 50),
        "sun_shadows": source.get("sun_shadows", 0),
    }


def normalise_authored_lighting_profile(value: Any) -> str:
    """Return the stable authored lighting profile key used by Map Studio."""

    text = str(value or "").strip().lower().replace("-", "_").replace(" ", "_")
    if text in {"fullbright", "fullbright_graybox", "graybox_fullbright", "debug_fullbright"}:
        return FULLBRIGHT_LIGHTING_PROFILE
    return text


def authored_lighting_metadata(module: AuthoredModuleMetadata) -> dict[str, Any]:
    """Return normalized module-level authored lighting metadata."""

    metadata = _dict(module.metadata)
    source = metadata.get("lighting")
    if source is None:
        source = metadata.get("lighting_profile")
    if source is None:
        source = _legacy_are_lighting_metadata(metadata.get("are"))
    if isinstance(source, dict):
        result = dict(source)
    elif isinstance(source, str) and source.strip():
        result = {"profile": source.strip()}
    else:
        result = {}
    if "profile" not in result and "mode" in result:
        result["profile"] = result.get("mode")
    if "profile" not in result and "status" in result:
        result["profile"] = result.get("status")
    result["profile"] = normalise_authored_lighting_profile(result.get("profile", ""))
    return result


def authored_area_metadata(
    module: AuthoredModuleMetadata,
    area: AuthoredAreaMetadata | None = None,
) -> AuthoredAreaMetadata:
    """Merge KMAP/stock-ARE area settings into the explicit area record.

    Older imported KMAPs stored raw ARE values under ``metadata['are']``;
    newer imports also provide the normalized ``metadata['area']`` mapping.
    This compatibility merge keeps both forms exportable without changing the
    caller-owned name, tag, comments, or gameplay flags.
    """

    current = area or AuthoredAreaMetadata()
    metadata = _dict(module.metadata)
    source = _dict(metadata.get("area"))
    legacy = _dict(metadata.get("are"))
    if not source:
        source = _dict(legacy.get("area"))
    if not source and legacy:
        source = {
            "fog_color": list(
                _packed_rgb(
                    legacy.get("fog_color", legacy.get("sun_fog_color")),
                    current.fog_color,
                )
            ),
            "fog_near": legacy.get("fog_near", legacy.get("sun_fog_near", current.fog_near)),
            "fog_far": legacy.get("fog_far", legacy.get("sun_fog_far", current.fog_far)),
            "sun_fog_on": legacy.get("sun_fog_on", current.sun_fog_on),
            "grass": {
                "texture": legacy.get("grass_tex_name", legacy.get("Grass_TexName", current.grass_texture)),
                "density": legacy.get("grass_density", legacy.get("Grass_Density", current.grass_density)),
                "quad_size": legacy.get("grass_quad_size", legacy.get("Grass_QuadSize", current.grass_quad_size)),
                "prob_ll": legacy.get("grass_prob_ll", legacy.get("Grass_Prob_LL", current.grass_prob_ll)),
                "prob_lr": legacy.get("grass_prob_lr", legacy.get("Grass_Prob_LR", current.grass_prob_lr)),
                "prob_ul": legacy.get("grass_prob_ul", legacy.get("Grass_Prob_UL", current.grass_prob_ul)),
                "prob_ur": legacy.get("grass_prob_ur", legacy.get("Grass_Prob_UR", current.grass_prob_ur)),
                "source": "legacy:are",
            },
        }
    if not source:
        return current

    fog_color = _rgb_tuple(source.get("fog_color"), current.fog_color)
    try:
        fog_near = float(source.get("fog_near", current.fog_near))
    except (TypeError, ValueError):
        fog_near = float(current.fog_near)
    try:
        fog_far = float(source.get("fog_far", current.fog_far))
    except (TypeError, ValueError):
        fog_far = float(current.fog_far)
    grass = _dict(source.get("grass"))
    grass_texture = str(
        grass.get("texture", source.get("grass_texture", source.get("grass_tex_name", current.grass_texture))) or ""
    ).strip().lower()

    def grass_value(key: str, fallback: float) -> float:
        try:
            value = float(grass.get(key, source.get(f"grass_{key}", fallback)))
        except (TypeError, ValueError):
            value = float(fallback)
        return max(0.0, value) if math.isfinite(value) else float(fallback)

    grass_density = grass_value("density", current.grass_density)
    grass_quad_size = grass_value("quad_size", current.grass_quad_size)
    grass_prob_ll = grass_value("prob_ll", current.grass_prob_ll)
    grass_prob_lr = grass_value("prob_lr", current.grass_prob_lr)
    grass_prob_ul = grass_value("prob_ul", current.grass_prob_ul)
    grass_prob_ur = grass_value("prob_ur", current.grass_prob_ur)
    return replace(
        current,
        fog_color=fog_color,
        fog_near=fog_near,
        fog_far=fog_far,
        sun_fog_on=bool(source.get("sun_fog_on", current.sun_fog_on)),
        grass_texture=grass_texture,
        grass_density=grass_density,
        grass_quad_size=grass_quad_size,
        grass_prob_ll=grass_prob_ll,
        grass_prob_lr=grass_prob_lr,
        grass_prob_ul=grass_prob_ul,
        grass_prob_ur=grass_prob_ur,
        metadata={
            **source,
            **dict(current.metadata),
            "world_lighting_source": str(source.get("source") or "kmap:area"),
            "grass_source": str(grass.get("source") or source.get("grass_source") or "kmap:area"),
        },
    )


def authored_lighting_profile(module: AuthoredModuleMetadata) -> str:
    """Return the authored lighting profile for export/readiness policy."""

    return normalise_authored_lighting_profile(authored_lighting_metadata(module).get("profile"))


def authored_lighting_is_fullbright(module: AuthoredModuleMetadata) -> bool:
    """Return True when the module should compile as a game-visible fullbright graybox."""

    return authored_lighting_profile(module) == FULLBRIGHT_LIGHTING_PROFILE


def _rgb_tuple(value: Any, fallback: RGB) -> RGB:
    if isinstance(value, (list, tuple)) and len(value) >= 3:
        try:
            return (
                max(0, min(255, int(value[0]))),
                max(0, min(255, int(value[1]))),
                max(0, min(255, int(value[2]))),
            )
        except (TypeError, ValueError):
            return fallback
    return fallback


def _clamped_byte(value: Any, fallback: int) -> int:
    try:
        return max(0, min(255, int(value)))
    except (TypeError, ValueError):
        return fallback


def authored_area_lighting_values(
    module: AuthoredModuleMetadata,
    area: AuthoredAreaMetadata | None = None,
    *,
    is_k2: bool = False,
) -> dict[str, Any]:
    """Return ARE lighting values after applying the authored lighting profile."""

    area = authored_area_metadata(module, area)
    lighting = authored_lighting_metadata(module)
    profile = authored_lighting_profile(module)
    if profile == FULLBRIGHT_LIGHTING_PROFILE:
        return {
            "profile": FULLBRIGHT_LIGHTING_PROFILE,
            "source": str(lighting.get("source") or "map_studio:authored:fullbright"),
            "sun_ambient": (255, 255, 255),
            "sun_diffuse": (255, 255, 255),
            "dynamic_ambient": (255, 255, 255),
            "shadow_opacity": 0,
            "sun_shadows": 0,
        }

    return {
        "profile": profile or "standard",
        "source": str(lighting.get("source") or "map_studio:authored:area_metadata"),
        "sun_ambient": _rgb_tuple(lighting.get("sun_ambient"), area.sun_ambient),
        "sun_diffuse": _rgb_tuple(lighting.get("sun_diffuse"), area.sun_diffuse),
        "dynamic_ambient": _rgb_tuple(
            lighting.get("dynamic_ambient") or lighting.get("dyn_ambient"),
            area.sun_ambient,
        ),
        "shadow_opacity": _clamped_byte(lighting.get("shadow_opacity"), 128 if is_k2 else 50),
        "sun_shadows": _clamped_byte(lighting.get("sun_shadows"), 0),
    }


def _script_field_name(value: Any, fields: tuple[str, ...]) -> str:
    wanted = str(value or "").strip().lower()
    for field_name in fields:
        if field_name.lower() == wanted:
            return field_name
    return ""


def _script_hook_source(metadata: dict[str, Any], *keys: str) -> dict[str, Any]:
    for key in keys:
        value = metadata.get(key)
        if isinstance(value, dict):
            return dict(value)
    return {}


def _normalise_script_hooks(*sources: dict[str, Any], fields: tuple[str, ...]) -> dict[str, str]:
    hooks: dict[str, str] = {}
    for source in sources:
        for field_name, script_resref in source.items():
            normalized_field = _script_field_name(field_name, fields)
            if not normalized_field:
                continue
            script = normalise_resref(script_resref)
            if script:
                hooks[normalized_field] = script
    return hooks


def authored_area_script_hooks(module: AuthoredModuleMetadata, area: AuthoredAreaMetadata | None = None) -> dict[str, str]:
    """Return normalized ARE script hooks authored in KMAP metadata."""

    area = authored_area_metadata(module, area)
    module_metadata = _dict(module.metadata)
    area_metadata = _dict(area.metadata)
    return _normalise_script_hooks(
        _script_hook_source(module_metadata, "area_scripts", "are_scripts"),
        _script_hook_source(area_metadata, "scripts", "area_scripts", "are_scripts"),
        fields=AREA_SCRIPT_FIELDS,
    )


def authored_module_script_hooks(module: AuthoredModuleMetadata) -> dict[str, str]:
    """Return normalized IFO/module script hooks authored in KMAP metadata."""

    module_metadata = _dict(module.metadata)
    return _normalise_script_hooks(
        _script_hook_source(module_metadata, "module_scripts", "ifo_scripts"),
        fields=MODULE_SCRIPT_FIELDS,
    )


def _validate_script_hook_source(
    *,
    source: Any,
    fields: tuple[str, ...],
    scope: str,
    blocking: list[str],
) -> None:
    if source in (None, ""):
        return
    if not isinstance(source, dict):
        blocking.append(f"{scope} script hooks must be stored as a field-to-resref mapping.")
        return
    known = ", ".join(fields)
    for field_name, script_resref in source.items():
        normalized_field = _script_field_name(field_name, fields)
        if not normalized_field:
            blocking.append(f"{scope} script field '{field_name}' is not supported. Known fields: {known}.")
            continue
        if str(script_resref or "").strip():
            issue = authored_resref_blocking_issue(f"{scope} script {normalized_field}", script_resref)
            if issue:
                blocking.append(issue)


def _set_empty_loc(root: Any, label: str) -> None:
    try:
        root.set_locstring(label, _empty_locstring())
    except Exception:
        root.set_string(label, "")


def _default_area_map_struct() -> Any:
    """Build the small minimap struct stock KOTOR ARE files carry."""

    item = _new_struct()
    item.set_int32("MapResX", 0)
    item.set_int32("NorthAxis", 0)
    item.set_single("WorldPt1X", -5.0)
    item.set_single("WorldPt1Y", -5.0)
    item.set_single("WorldPt2X", 5.0)
    item.set_single("WorldPt2Y", 5.0)
    item.set_single("MapPt1X", 0.0)
    item.set_single("MapPt1Y", 0.0)
    item.set_single("MapPt2X", 1.0)
    item.set_single("MapPt2Y", 1.0)
    item.set_int32("MapZoom", 1)
    return item


def _normalised_unique_room_resrefs(room_resrefs: tuple[str, ...], fallback: str) -> tuple[str, ...]:
    seen: set[str] = set()
    rooms: list[str] = []
    for raw in room_resrefs or ():
        room = normalise_resref(raw)
        if room and room not in seen:
            seen.add(room)
            rooms.append(room)
    if not rooms and fallback:
        rooms.append(normalise_resref(fallback))
    return tuple(rooms)


def _room_list(room_resrefs: tuple[str, ...], fallback: str) -> Any:
    """Build ARE Rooms entries naming the room MDL/WOK resources."""

    rooms = _empty_gff_list()
    for index, room in enumerate(_normalised_unique_room_resrefs(room_resrefs, fallback)):
        item = rooms.add(index)
        item.set_string("RoomName", room)
        item.set_int32("EnvAudio", 0)
        item.set_single("AmbientScale", 1.0)
    return rooms


def _area_list(area_resref: str) -> Any:
    """Build IFO Mod_Area_list with the authored area resref."""

    areas = _empty_gff_list()
    item = areas.add(6)
    item.set_resref("Area_Name", normalise_resref(area_resref))
    return areas


def validate_authored_module_metadata(
    module: AuthoredModuleMetadata,
    entry_point: ModuleEntryPoint,
    area: AuthoredAreaMetadata | None = None,
    time: AuthoredModuleTimeMetadata | None = None,
) -> AuthoredModuleMetadataValidation:
    """Validate ARE/IFO metadata before serialization."""

    area = authored_area_metadata(module, area)
    time = time or AuthoredModuleTimeMetadata()
    warnings: list[str] = []
    blocking: list[str] = []
    module_root = module.normalised_root()
    module_issue = authored_resref_blocking_issue("Authored module metadata", module.module_root)
    if module_issue:
        blocking.append(module_issue)
    entry_area = normalise_resref(entry_point.area_resref)
    entry_issue = authored_resref_blocking_issue("Module entry area", entry_point.area_resref)
    if entry_issue:
        blocking.append(entry_issue)
    if entry_area and module_root and entry_area != module_root:
        blocking.append(f"Module entry area {entry_area} does not match module resref {module_root}.")
    if not str(module.display_name or area.name or "").strip():
        warnings.append("Module has no display name; in-game UI may show a blank area name.")
    if float(area.fog_far) < float(area.fog_near):
        blocking.append("Fog far distance must be greater than or equal to fog near distance.")
    if not (0 <= int(time.dawn_hour) <= 23):
        blocking.append("Dawn hour must be between 0 and 23.")
    if not (0 <= int(time.dusk_hour) <= 23):
        blocking.append("Dusk hour must be between 0 and 23.")
    if int(time.minutes_per_hour) <= 0:
        blocking.append("Minutes per hour must be positive.")
    module_metadata = _dict(module.metadata)
    area_metadata = _dict(area.metadata)
    _validate_script_hook_source(
        source=module_metadata.get("module_scripts", module_metadata.get("ifo_scripts")),
        fields=MODULE_SCRIPT_FIELDS,
        scope="Module",
        blocking=blocking,
    )
    _validate_script_hook_source(
        source=module_metadata.get("area_scripts", module_metadata.get("are_scripts")),
        fields=AREA_SCRIPT_FIELDS,
        scope="Area",
        blocking=blocking,
    )
    _validate_script_hook_source(
        source=area_metadata.get("scripts", area_metadata.get("area_scripts", area_metadata.get("are_scripts"))),
        fields=AREA_SCRIPT_FIELDS,
        scope="Area",
        blocking=blocking,
    )
    return AuthoredModuleMetadataValidation(
        ok=not blocking,
        warnings=tuple(warnings),
        blocking_issues=tuple(blocking),
    )


def build_authored_are_gff(
    module: AuthoredModuleMetadata,
    area: AuthoredAreaMetadata | None = None,
    *,
    room_resrefs: tuple[str, ...] = (),
) -> Any:
    """Build an ARE GFF from authored area metadata."""

    area = authored_area_metadata(module, area)
    root_resref = module.normalised_root()
    display_name = str(area.name or module.display_name or root_resref)
    tag = normalise_resref(area.tag or module.tag or root_resref)
    is_k2 = _is_k2_game(module.game)
    lighting = authored_area_lighting_values(module, area, is_k2=is_k2)
    sun_fog_on = bool(area.sun_fog_on) and lighting["profile"] != FULLBRIGHT_LIGHTING_PROFILE
    gff = _new_gff("ARE")
    root = gff.root
    root.set_int32("ID", 0)
    root.set_int32("Creator_ID", 0)
    root.set_uint32("Version", _are_version_for_game(module.game))
    _set_loc(root, "Name", display_name)
    root.set_string("Tag", tag)
    root.set_string("Comments", area.comments)
    root.set_struct("Map", _default_area_map_struct())
    root.set_list("Expansion_List", _empty_gff_list())
    root.set_uint32("Flags", 7 if not is_k2 else 0)
    root.set_int32("ModSpotCheck", 0)
    root.set_int32("ModListenCheck", 0)
    root.set_single("AlphaTest", 0.2)
    root.set_int32("CameraStyle", 1 if not is_k2 else 0)
    _set_empty_resref(root, "DefaultEnvMap")
    root.set_resref("Grass_TexName", str(area.grass_texture or ""))
    root.set_single("Grass_Density", float(area.grass_density))
    root.set_single("Grass_QuadSize", float(area.grass_quad_size))
    root.set_uint32("Grass_Ambient", 0)
    root.set_uint32("Grass_Diffuse", 0)
    root.set_single("Grass_Prob_LL", float(area.grass_prob_ll))
    root.set_single("Grass_Prob_LR", float(area.grass_prob_lr))
    root.set_single("Grass_Prob_UL", float(area.grass_prob_ul))
    root.set_single("Grass_Prob_UR", float(area.grass_prob_ur))
    root.set_uint32("MoonAmbientColor", 0)
    root.set_uint32("MoonDiffuseColor", 0)
    root.set_uint8("MoonFogOn", 0)
    root.set_single("MoonFogNear", float(area.fog_near) if is_k2 else 99.0)
    root.set_single("MoonFogFar", float(area.fog_far) if is_k2 else 100.0)
    root.set_uint32("MoonFogColor", 0)
    root.set_uint8("MoonShadows", 0)
    root.set_uint8("Unescapable", _byte(area.unescapable or not is_k2))
    if is_k2:
        root.set_uint8("DisableTransit", _byte(area.disable_transit))
        root.set_uint8("Natural", _byte(area.natural))
    root.set_uint8("PlayerVsPlayer", _byte(area.player_vs_player))
    root.set_uint8("NoRest", _byte(area.no_rest))
    root.set_uint8("NoHangBack", 0)
    root.set_uint8("PlayerOnly", 0)
    root.set_uint8("StealthXPEnabled", 0)
    root.set_uint32("StealthXPLoss", 0)
    root.set_uint32("StealthXPMax", 0)
    root.set_uint32("SunAmbientColor", _rgb(lighting["sun_ambient"]))
    root.set_uint32("SunDiffuseColor", _rgb(lighting["sun_diffuse"]))
    if is_k2:
        root.set_uint32("FogColor", _rgb(area.fog_color))
        root.set_single("FogNearDist", float(area.fog_near))
        root.set_single("FogFarDist", float(area.fog_far))
        root.set_uint8("SunFog", _byte(sun_fog_on))
    root.set_uint8("SunFogOn", _byte(sun_fog_on))
    root.set_single("SunFogNear", float(area.fog_near))
    root.set_single("SunFogFar", float(area.fog_far))
    root.set_uint32("SunFogColor", _rgb(area.fog_color))
    root.set_uint8("SunShadows", int(lighting["sun_shadows"]))
    root.set_uint32("DynAmbientColor", _rgb(lighting["dynamic_ambient"]))
    root.set_uint8("IsNight", 0)
    root.set_uint8("LightingScheme", 0)
    root.set_uint8("ShadowOpacity", int(lighting["shadow_opacity"]))
    root.set_uint8("DayNightCycle", 0)
    root.set_int32("ChanceRain", 0)
    root.set_int32("ChanceSnow", 0)
    root.set_int32("ChanceLightning", 0)
    root.set_int32("WindPower", 0)
    root.set_uint16("LoadScreenID", 0)
    root.set_list("Rooms", _room_list(room_resrefs, root_resref))
    for label in AREA_SCRIPT_FIELDS:
        _set_empty_resref(root, label)
    for label, script in authored_area_script_hooks(module, area).items():
        root.set_resref(label, script)
    return gff


def build_authored_ifo_gff(
    module: AuthoredModuleMetadata,
    entry_point: ModuleEntryPoint,
    time: AuthoredModuleTimeMetadata | None = None,
    *,
    area_resrefs: tuple[str, ...] = (),
) -> Any:
    """Build an IFO GFF from authored module metadata and entry point."""

    time = time or AuthoredModuleTimeMetadata()
    root_resref = module.normalised_root()
    display_name = str(module.display_name or root_resref)
    voice_over_id = normalise_resref(
        str(module.metadata.get("voice_over_id") or root_resref)
    )
    gff = _new_gff("IFO")
    root = gff.root
    root.set_binary("Mod_ID", _module_id_bytes(root_resref))
    root.set_int32("Mod_Creator_ID", 0)
    root.set_uint32("Mod_Version", 3)
    root.set_string("Mod_VO_ID", voice_over_id)
    root.set_uint16("Expansion_Pack", int(time.expansion_pack))
    _set_loc(root, "Mod_Name", display_name)
    root.set_string("Mod_Tag", "MODULE")
    root.set_string("Mod_Hak", "")
    _set_empty_loc(root, "Mod_Description")
    root.set_uint8("Mod_IsSaveGame", 0)
    apply_entry_point_to_ifo(root, entry_point)
    root.set_list("Mod_Expan_List", _empty_gff_list())
    root.set_uint8("Mod_DawnHour", int(time.dawn_hour))
    root.set_uint8("Mod_DuskHour", int(time.dusk_hour))
    root.set_uint8("Mod_MinPerHour", int(time.minutes_per_hour))
    root.set_uint8("Mod_StartMonth", 1)
    root.set_uint8("Mod_StartDay", 1)
    root.set_uint8("Mod_StartHour", int(time.dawn_hour))
    root.set_uint32("Mod_StartYear", 0)
    root.set_uint8("Mod_XPScale", 10)
    for label in (*MODULE_SCRIPT_FIELDS, "Mod_StartMovie"):
        _set_empty_resref(root, label)
    for label, script in authored_module_script_hooks(module).items():
        root.set_resref(label, script)
    root.set_list("Mod_CutSceneList", _empty_gff_list())
    root.set_list("Mod_GVar_List", _empty_gff_list())
    area_names = tuple(normalise_resref(value) for value in area_resrefs if normalise_resref(value))
    root.set_list("Mod_Area_list", _area_list(area_names[0] if area_names else entry_point.area_resref))
    return gff


def build_authored_are_bytes(
    module: AuthoredModuleMetadata,
    area: AuthoredAreaMetadata | None = None,
    *,
    room_resrefs: tuple[str, ...] = (),
) -> bytes:
    return _bytes_gff(build_authored_are_gff(module, area, room_resrefs=room_resrefs))


def patch_preserved_stock_are_bytes(
    source_are_bytes: bytes,
    module: AuthoredModuleMetadata,
    area: AuthoredAreaMetadata | None = None,
    *,
    room_resrefs: tuple[str, ...] = (),
    update_world_lighting: bool = False,
) -> bytes:
    """Patch only Map Studio-owned fields into an imported stock ARE.

    Unknown moon/weather/grass/audio fields and K1/K2 field presence remain
    byte-for-byte untouched when no authored change is needed.  When rooms or
    world lighting change, the source GFF is reserialized but unowned fields
    and existing per-room structs are preserved semantically.
    """

    raw = bytes(source_are_bytes or b"")
    if not raw:
        return build_authored_are_bytes(module, area, room_resrefs=room_resrefs)
    from pykotor.resource.formats.gff import read_gff

    source = read_gff(raw)
    target_rooms = _normalised_unique_room_resrefs(room_resrefs, module.normalised_root())
    existing_rooms = tuple(source.root.acquire("Rooms", ()) or ())
    existing_names = tuple(
        normalise_resref(str(room.acquire("RoomName", "") or ""))
        for room in existing_rooms
        if normalise_resref(str(room.acquire("RoomName", "") or ""))
    )
    if not update_world_lighting and existing_names == target_rooms:
        return raw

    candidate = build_authored_are_gff(module, area, room_resrefs=target_rooms)
    if update_world_lighting:
        setters = {
            "SunAmbientColor": source.root.set_uint32,
            "SunDiffuseColor": source.root.set_uint32,
            "DynAmbientColor": source.root.set_uint32,
            "ShadowOpacity": source.root.set_uint8,
            "SunShadows": source.root.set_uint8,
            "SunFogOn": source.root.set_uint8,
            "SunFogNear": source.root.set_single,
            "SunFogFar": source.root.set_single,
            "SunFogColor": source.root.set_uint32,
            "FogColor": source.root.set_uint32,
            "FogNearDist": source.root.set_single,
            "FogFarDist": source.root.set_single,
            "SunFog": source.root.set_uint8,
        }
        for label, setter in setters.items():
            # Preserve the exact vanilla field-presence contract. In
            # particular, K2 001ebo omits the Fog*/SunFog alias fields.
            if label in source.root and label in candidate.root:
                setter(label, candidate.root.get(label))

    if existing_names != target_rooms:
        existing_by_name = {
            normalise_resref(str(room.acquire("RoomName", "") or "")): room
            for room in existing_rooms
        }
        candidate_by_name = {
            normalise_resref(str(room.acquire("RoomName", "") or "")): room
            for room in tuple(candidate.root.acquire("Rooms", ()) or ())
        }
        patched_rooms = _empty_gff_list()
        for room_name in target_rooms:
            # GFFStruct implements collection-like truthiness, so a valid
            # imported room struct may evaluate false and must not be selected
            # with ``existing or generated``.  Preserve it by identity unless
            # it is genuinely absent.
            room = existing_by_name.get(room_name)
            if room is None:
                room = candidate_by_name.get(room_name)
            if room is not None:
                patched_rooms.append(room)
        source.root.set_list("Rooms", patched_rooms)
    return _bytes_gff(source)


def patch_preserved_stock_ifo_bytes(
    source_ifo_bytes: bytes,
    entry_point: ModuleEntryPoint,
    *,
    area_resrefs: tuple[str, ...] = (),
) -> bytes:
    """Patch only entry/area routing into an imported stock IFO.

    Module script hooks, globals, VO identity, time settings, localized names,
    and unknown fields remain untouched.  A byte-identical result is returned
    when the source already names the requested entry point and area list.
    """

    raw = bytes(source_ifo_bytes or b"")
    if not raw:
        raise ValueError("A preserved stock IFO byte stream is required.")
    from pykotor.resource.formats.gff import read_gff

    source = read_gff(raw)
    root = source.root
    target_area_names = tuple(
        normalise_resref(value) for value in area_resrefs if normalise_resref(value)
    ) or (normalise_resref(entry_point.area_resref),)
    current_area_names = tuple(
        normalise_resref(str(item.acquire("Area_Name", "") or ""))
        for item in tuple(root.acquire("Mod_Area_list", ()) or ())
        if normalise_resref(str(item.acquire("Area_Name", "") or ""))
    )
    expected_direction = (math.cos(float(entry_point.facing)), math.sin(float(entry_point.facing)))
    current_values = (
        normalise_resref(str(root.acquire("Mod_Entry_Area", "") or "")),
        float(root.acquire("Mod_Entry_X", 0.0) or 0.0),
        float(root.acquire("Mod_Entry_Y", 0.0) or 0.0),
        float(root.acquire("Mod_Entry_Z", 0.0) or 0.0),
        float(root.acquire("Mod_Entry_Dir_X", 1.0) or 0.0),
        float(root.acquire("Mod_Entry_Dir_Y", 0.0) or 0.0),
    )
    expected_values = (
        normalise_resref(entry_point.area_resref),
        float(entry_point.position[0]),
        float(entry_point.position[1]),
        float(entry_point.position[2]),
        expected_direction[0],
        expected_direction[1],
    )
    values_match = current_values[0] == expected_values[0] and all(
        abs(float(current_values[index]) - float(expected_values[index])) <= 1.0e-6
        for index in range(1, len(current_values))
    )
    if values_match and current_area_names == target_area_names:
        return raw

    apply_entry_point_to_ifo(root, entry_point)
    if current_area_names != target_area_names:
        root.set_list("Mod_Area_list", _area_list(target_area_names[0]))
    return _bytes_gff(source)


def build_authored_ifo_bytes(
    module: AuthoredModuleMetadata,
    entry_point: ModuleEntryPoint,
    time: AuthoredModuleTimeMetadata | None = None,
    *,
    area_resrefs: tuple[str, ...] = (),
) -> bytes:
    return _bytes_gff(build_authored_ifo_gff(module, entry_point, time, area_resrefs=area_resrefs))


def compile_authored_module_metadata(
    module: AuthoredModuleMetadata,
    entry_point: ModuleEntryPoint,
    *,
    area: AuthoredAreaMetadata | None = None,
    time: AuthoredModuleTimeMetadata | None = None,
    room_resrefs: tuple[str, ...] = (),
    area_resrefs: tuple[str, ...] = (),
) -> CompiledAuthoredModuleMetadata:
    """Compile authored metadata into serialized ARE/IFO bytes."""

    validation = validate_authored_module_metadata(module, entry_point, area, time)
    if not validation.ok:
        raise ValueError("; ".join(validation.blocking_issues))
    area = authored_area_metadata(module, area)
    time = time or AuthoredModuleTimeMetadata()
    module_root = module.normalised_root()
    lighting = authored_area_lighting_values(module, area, is_k2=_is_k2_game(module.game))
    area_names = tuple(normalise_resref(value) for value in area_resrefs if normalise_resref(value))
    if not area_names:
        area_names = (normalise_resref(entry_point.area_resref),)
    return CompiledAuthoredModuleMetadata(
        are_bytes=build_authored_are_bytes(module, area, room_resrefs=room_resrefs),
        ifo_bytes=build_authored_ifo_bytes(module, entry_point, time, area_resrefs=area_names),
        validation=validation,
        metadata={
            "source": "src.core.modules.authored_module_metadata",
            "module_root": module_root,
            "display_name": module.display_name,
            "tag": normalise_resref(module.tag or module.module_root),
            "room_resrefs": list(_normalised_unique_room_resrefs(room_resrefs, module_root)),
            "area_resrefs": list(area_names),
            "fog_near": float(area.fog_near),
            "fog_far": float(area.fog_far),
            "lighting_profile": lighting["profile"],
            "lighting": {
                "profile": lighting["profile"],
                "source": lighting["source"],
                "sun_ambient": list(lighting["sun_ambient"]),
                "sun_diffuse": list(lighting["sun_diffuse"]),
                "dynamic_ambient": list(lighting["dynamic_ambient"]),
                "shadow_opacity": int(lighting["shadow_opacity"]),
                "sun_shadows": int(lighting["sun_shadows"]),
            },
            "sun_ambient": list(lighting["sun_ambient"]),
            "sun_diffuse": list(lighting["sun_diffuse"]),
            "dynamic_ambient": list(lighting["dynamic_ambient"]),
            "shadow_opacity": int(lighting["shadow_opacity"]),
            "sun_shadows": int(lighting["sun_shadows"]),
            "dawn_hour": int(time.dawn_hour),
            "dusk_hour": int(time.dusk_hour),
            "area_scripts": authored_area_script_hooks(module, area),
            "module_scripts": authored_module_script_hooks(module),
        },
    )


__all__ = [
    "AuthoredAreaMetadata",
    "AREA_SCRIPT_FIELDS",
    "AuthoredModuleMetadataValidation",
    "AuthoredModuleTimeMetadata",
    "FULLBRIGHT_LIGHTING_PROFILE",
    "MODULE_SCRIPT_FIELDS",
    "CompiledAuthoredModuleMetadata",
    "authored_area_metadata",
    "authored_area_lighting_values",
    "authored_area_script_hooks",
    "authored_lighting_is_fullbright",
    "authored_lighting_metadata",
    "authored_lighting_profile",
    "authored_module_id_bytes",
    "authored_module_script_hooks",
    "build_authored_are_bytes",
    "patch_preserved_stock_are_bytes",
    "build_authored_are_gff",
    "build_authored_ifo_bytes",
    "build_authored_ifo_gff",
    "compile_authored_module_metadata",
    "normalise_authored_lighting_profile",
    "validate_authored_module_metadata",
]
