"""Fallback tokens for GhostRigger themes and layouts."""

from __future__ import annotations

LEGACY_MATRIX_COLORS: dict[str, str] = {
    "bg": "#0B0F0D",
    "bg2": "#07100C",
    "panel": "#111916",
    "panel2": "#151D1A",
    "border": "#1B2A22",
    "hover": "#183428",
    "selected": "#00FF7A",
    "accent": "#00FF7A",
    "accent2": "#00D7B5",
    "text": "#E8F0EC",
    "text2": "#7A9A88",
    "success": "#00FF7A",
    "warning": "#FFAA00",
    "error": "#FF4444",
    "gold": "#D8C66A",
}

TOKEN_ALIASES: dict[str, str] = {
    "bg": "window.background",
    "bg2": "viewport.background",
    "panel": "panel.background",
    "panel2": "panel.backgroundAlt",
    "border": "panel.border",
    "hover": "button.hover",
    "selected": "selection.background",
    "accent": "accent.primary",
    "accent2": "accent.secondary",
    "text": "text.primary",
    "text2": "text.secondary",
    "gold": "text.gold",
}

FALLBACK_COLORS: dict[str, str] = {
    "window.background": LEGACY_MATRIX_COLORS["bg"],
    "window.text": LEGACY_MATRIX_COLORS["text"],
    "panel.background": LEGACY_MATRIX_COLORS["panel"],
    "panel.backgroundAlt": LEGACY_MATRIX_COLORS["panel2"],
    "panel.altBackground": LEGACY_MATRIX_COLORS["panel2"],
    "panel.border": LEGACY_MATRIX_COLORS["border"],
    "panel.headerBackground": LEGACY_MATRIX_COLORS["panel2"],
    "panel.headerText": LEGACY_MATRIX_COLORS["text"],
    "groupbox.border": LEGACY_MATRIX_COLORS["border"],
    "groupbox.title": LEGACY_MATRIX_COLORS["gold"],
    "viewport.background": LEGACY_MATRIX_COLORS["bg2"],
    "viewport.border": "#34383F",
    "viewport.text": "#8F9AAA",
    "viewport.gridMajor": "#1D3A2B",
    "viewport.gridMinor": "#102019",
    "viewport.helper.meshHover": "#00D7B5",
    "viewport.helper.light": "#FFD24A",
    "viewport.helper.lightSelected": "#E6F2FF",
    "viewport.helper.camera": "#B4D2DC",
    "viewport.helper.cameraSelected": "#FFD658",
    "viewport.helper.null": "#A3B8D1",
    "viewport.helper.nullSelected": "#FFD658",
    "toolbar.background": LEGACY_MATRIX_COLORS["panel"],
    "toolbar.border": LEGACY_MATRIX_COLORS["border"],
    "viewportToolbar.background": LEGACY_MATRIX_COLORS["panel"],
    "viewportToolbar.border": LEGACY_MATRIX_COLORS["border"],
    "button.background": LEGACY_MATRIX_COLORS["panel2"],
    "button.hover": LEGACY_MATRIX_COLORS["hover"],
    "button.pressed": "#102019",
    "button.checked": LEGACY_MATRIX_COLORS["accent"],
    "button.checkedText": "#001A0E",
    "button.text": LEGACY_MATRIX_COLORS["text"],
    "button.accentText": "#001A0E",
    "button.disabledBackground": LEGACY_MATRIX_COLORS["panel"],
    "button.disabledText": "#55665B",
    "input.background": LEGACY_MATRIX_COLORS["panel2"],
    "input.text": LEGACY_MATRIX_COLORS["text"],
    "input.border": LEGACY_MATRIX_COLORS["border"],
    "input.focusBorder": LEGACY_MATRIX_COLORS["accent2"],
    "spinbox.buttonBackground": "#26312C",
    "spinbox.buttonHover": LEGACY_MATRIX_COLORS["hover"],
    "spinbox.buttonPressed": "#102019",
    "spinbox.buttonBorder": "#3B5147",
    "spinbox.arrow": LEGACY_MATRIX_COLORS["text"],
    "tab.background": LEGACY_MATRIX_COLORS["panel"],
    "tab.selectedBackground": LEGACY_MATRIX_COLORS["bg2"],
    "tab.inactiveBackground": LEGACY_MATRIX_COLORS["panel"],
    "tab.text": LEGACY_MATRIX_COLORS["text2"],
    "tab.selectedText": LEGACY_MATRIX_COLORS["accent"],
    "table.background": LEGACY_MATRIX_COLORS["bg2"],
    "table.text": LEGACY_MATRIX_COLORS["text"],
    "table.headerBackground": LEGACY_MATRIX_COLORS["panel2"],
    "table.headerText": LEGACY_MATRIX_COLORS["text"],
    "table.grid": LEGACY_MATRIX_COLORS["border"],
    "tree.background": LEGACY_MATRIX_COLORS["bg2"],
    "tree.text": LEGACY_MATRIX_COLORS["text"],
    "scrollbar.background": LEGACY_MATRIX_COLORS["panel"],
    "scrollbar.handle": LEGACY_MATRIX_COLORS["border"],
    "selection.background": LEGACY_MATRIX_COLORS["selected"],
    "selection.text": "#FFFFFF",
    "text.primary": LEGACY_MATRIX_COLORS["text"],
    "text.secondary": LEGACY_MATRIX_COLORS["text2"],
    "text.disabled": "#55665B",
    "text.gold": LEGACY_MATRIX_COLORS["gold"],
    "accent.primary": LEGACY_MATRIX_COLORS["accent"],
    "accent.secondary": LEGACY_MATRIX_COLORS["accent2"],
    "axis.x": "#FF5A5F",
    "axis.y": LEGACY_MATRIX_COLORS["accent"],
    "axis.z": "#4FA3FF",
    "axis.text": "#001A0E",
    "transformBar.background": LEGACY_MATRIX_COLORS["panel"],
    "transformBar.border": LEGACY_MATRIX_COLORS["border"],
    "splash.background": LEGACY_MATRIX_COLORS["bg"],
    "splash.panel": LEGACY_MATRIX_COLORS["panel"],
    "splash.brandBackground": LEGACY_MATRIX_COLORS["panel2"],
    "splash.progressBackground": LEGACY_MATRIX_COLORS["panel2"],
    "splash.border": LEGACY_MATRIX_COLORS["accent"],
    "splash.text": LEGACY_MATRIX_COLORS["text"],
    "splash.secondaryText": LEGACY_MATRIX_COLORS["text2"],
    "splash.accent": LEGACY_MATRIX_COLORS["accent"],
    "splash.progressTrack": LEGACY_MATRIX_COLORS["panel2"],
    "splash.progressFill": LEGACY_MATRIX_COLORS["success"],
    "matrixBar.background": LEGACY_MATRIX_COLORS["bg"],
    "matrixBar.glyph": LEGACY_MATRIX_COLORS["accent"],
    "matrixBar.text": LEGACY_MATRIX_COLORS["accent"],
    "matrixBar.subtext": LEGACY_MATRIX_COLORS["text2"],
    "matrixBar.metaText": LEGACY_MATRIX_COLORS["text2"],
    "matrixBar.ipcText": LEGACY_MATRIX_COLORS["accent"],
    "info": LEGACY_MATRIX_COLORS["accent2"],
    "warning": LEGACY_MATRIX_COLORS["warning"],
    "error": LEGACY_MATRIX_COLORS["error"],
    "success": LEGACY_MATRIX_COLORS["success"],
}

NATIVE_FALLBACK_COLORS: dict[str, str] = {
    "window.background": "#F3F3F3",
    "window.text": "#20242A",
    "panel.background": "#FFFFFF",
    "panel.backgroundAlt": "#EEF1F5",
    "panel.altBackground": "#EEF1F5",
    "panel.border": "#B8C0CC",
    "panel.headerBackground": "#E7EAF0",
    "panel.headerText": "#20242A",
    "groupbox.border": "#B8C0CC",
    "groupbox.title": "#284C7E",
    "viewport.background": "#F8F9FB",
    "viewport.border": "#B8C0CC",
    "viewport.text": "#5E6977",
    "viewport.gridMajor": "#D5DAE1",
    "viewport.gridMinor": "#E5E8EE",
    "viewport.helper.meshHover": "#00D7B5",
    "viewport.helper.light": "#FFD24A",
    "viewport.helper.lightSelected": "#1F6FEB",
    "viewport.helper.camera": "#52616F",
    "viewport.helper.cameraSelected": "#9A6700",
    "viewport.helper.null": "#5E6977",
    "viewport.helper.nullSelected": "#1F6FEB",
    "toolbar.background": "#F3F3F3",
    "toolbar.border": "#C4CBD5",
    "viewportToolbar.background": "#F3F3F3",
    "viewportToolbar.border": "#C4CBD5",
    "button.background": "#F7F8FA",
    "button.hover": "#E8EEF6",
    "button.pressed": "#D9E2EC",
    "button.checked": "#1F6FEB",
    "button.checkedText": "#FFFFFF",
    "button.text": "#20242A",
    "button.accentText": "#FFFFFF",
    "button.disabledBackground": "#ECEFF3",
    "button.disabledText": "#7A8490",
    "input.background": "#FFFFFF",
    "input.text": "#20242A",
    "input.border": "#B8C0CC",
    "input.focusBorder": "#1F6FEB",
    "spinbox.buttonBackground": "#E1E7EF",
    "spinbox.buttonHover": "#D4DEE9",
    "spinbox.buttonPressed": "#C4D1DE",
    "spinbox.buttonBorder": "#AEB8C4",
    "spinbox.arrow": "#20242A",
    "tab.background": "#ECEFF3",
    "tab.selectedBackground": "#FFFFFF",
    "tab.inactiveBackground": "#E5E9EF",
    "tab.text": "#5E6977",
    "tab.selectedText": "#20242A",
    "table.background": "#FFFFFF",
    "table.text": "#20242A",
    "table.headerBackground": "#E7EAF0",
    "table.headerText": "#20242A",
    "table.grid": "#D2D8E0",
    "tree.background": "#FFFFFF",
    "tree.text": "#20242A",
    "scrollbar.background": "#ECEFF3",
    "scrollbar.handle": "#AEB8C4",
    "selection.background": "#1F6FEB",
    "selection.text": "#FFFFFF",
    "text.primary": "#20242A",
    "text.secondary": "#5E6977",
    "text.disabled": "#7A8490",
    "text.gold": "#8A6A00",
    "accent.primary": "#1F6FEB",
    "accent.secondary": "#008C7E",
    "axis.x": "#C93434",
    "axis.y": "#1B8F45",
    "axis.z": "#1F6FEB",
    "axis.text": "#FFFFFF",
    "transformBar.background": "#F3F3F3",
    "transformBar.border": "#C4CBD5",
    "splash.background": "#F3F3F3",
    "splash.panel": "#FFFFFF",
    "splash.brandBackground": "#EEF1F5",
    "splash.progressBackground": "#F8F9FB",
    "splash.border": "#B8C0CC",
    "splash.text": "#20242A",
    "splash.secondaryText": "#5E6977",
    "splash.accent": "#1F6FEB",
    "splash.progressTrack": "#FFFFFF",
    "splash.progressFill": "#1B8F45",
    "matrixBar.background": "#EAF0F7",
    "matrixBar.glyph": "#1F6FEB",
    "matrixBar.text": "#1F4F8F",
    "matrixBar.subtext": "#5E6977",
    "matrixBar.metaText": "#5E6977",
    "matrixBar.ipcText": "#008C7E",
    "info": "#1670B7",
    "warning": "#9A6700",
    "error": "#C93434",
    "success": "#1B8F45",
}

FALLBACK_FONTS: dict[str, dict[str, str | int]] = {
    "default": {"family": "Consolas", "size": 9, "weight": "normal"},
    "monospace": {"family": "Consolas", "size": 9, "weight": "normal"},
    "heading": {"family": "Segoe UI", "size": 10, "weight": "bold"},
    "small": {"family": "Segoe UI", "size": 8, "weight": "normal"},
    "viewport": {"family": "Consolas", "size": 9, "weight": "normal"},
    "terminal": {"family": "Consolas", "size": 9, "weight": "normal"},
    "matrix": {"family": "Aurebesh AF", "size": 9, "weight": "normal"},
}

FALLBACK_STYLES: dict[str, str] = {
    "application.native": "false",
    "matrixBar.style": "matrix",
    "matrixBar.glyphs": "",
    "matrixBar.fontFamily": "",
    "matrixBar.imagePath": "",
    "matrixBar.cropX": "0",
    "matrixBar.cropY": "0",
    "matrixBar.cropW": "100",
    "matrixBar.cropH": "100",
    "splash.logoPath": "",
    "splash.productText": "GhostStudio",
    "splash.subtitleText": "Odyssey Engine Pipeline",
    "splash.copyrightText": "GhostStudio (C) 2026 Shaolin (CrispyWonton). Co-developed by LordVaderCW.",
    "splash.surfaceStyle": "matte",
    "tab.mode": "standard",
}

VALID_TAB_STYLE_MODES = {
    "standard",
    "flat",
    "beveled",
}

FALLBACK_METRICS: dict[str, int] = {
    "window.defaultWidth": 1650,
    "window.defaultHeight": 920,
    "toolbar.height": 34,
    "toolbar.iconSize": 18,
    "toolbar.buttonHeight": 16,
    "toolbar.buttonMinWidth": 64,
    "toolbar.spacing": 4,
    "button.height": 16,
    "button.minWidth": 64,
    "button.paddingX": 6,
    "button.paddingY": 1,
    "button.paddingH": 6,
    "button.paddingV": 1,
    "input.height": 24,
    "input.minWidth": 90,
    "combo.height": 24,
    "spinbox.height": 24,
    "spinbox.buttonWidth": 16,
    "checkbox.spacing": 4,
    "tab.height": 14,
    "tab.width": 78,
    "tab.padding": 8,
    "tab.paddingX": 12,
    "tab.paddingY": 6,
    "tab.margin": 0,
    "tab.marginX": 0,
    "tab.marginY": 0,
    "panel.margin": 4,
    "panel.spacing": 4,
    "panel.headerHeight": 28,
    "panel.minWidth": 260,
    "panel.preferredWidth": 360,
    "leftPanel.preferredWidth": 390,
    "rightPanel.preferredWidth": 390,
    "farRightPanel.preferredWidth": 380,
    "splitter.handleWidth": 6,
    "groupbox.margin": 8,
    "groupbox.spacing": 4,
    "table.rowHeight": 22,
    "tree.rowHeight": 22,
    "statusbar.height": 24,
    "transformBar.height": 30,
    "viewportToolbar.height": 34,
    "splash.width": 960,
    "splash.height": 540,
    "splash.logoSize": 300,
    "bottom.preferredHeight": 220,
    "bottomPanel.preferredHeight": 220,
    "bottom.minHeight": 120,
    "viewport.minWidth": 500,
    "border.radius": 3,
}

VALID_BUTTON_MODES = {
    "iconOnly",
    "textOnly",
    "iconText",
    "textBesideIcon",
    "textUnderIcon",
}


def color_alias_view(colors: dict[str, str]) -> dict[str, str]:
    """Return the legacy ``C`` dictionary view for older GUI modules."""

    view: dict[str, str] = {}
    for legacy_key, token in TOKEN_ALIASES.items():
        view[legacy_key] = colors.get(token, FALLBACK_COLORS[token])
    for key in ("success", "warning", "error"):
        view[key] = colors.get(key, FALLBACK_COLORS[key])
    return view
